module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    concat: {
      options: {
        stripBanners: false,
        banner: '/**\n' +
                ' * <%= pkg.name %> v<%= pkg.version %>\n' +
                ' * This file is generated by grunt. Do not edit!\n' +
                ' * Date: <%= grunt.template.today("yyyy-mm-dd HH:MM:ss") %>\n' +
                ' */\n\n',
      },
      dist: {
        src: ['src/*.js'],
        dest: 'demo/javascripts/main.js'
      }
    },

    watch: {
      files: ['src/*.js'],
      tasks: ['concat']
    },

    copy: {
      main: {
        files: [
          {
            expand: true,
            cwd: 'ace-builds/src-noconflict/',
            src: ['**'],
            dest: 'demo/javascripts/ace'
          }
        ]
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.registerTask('copy_ace_build', ['copy']);
  grunt.registerTask('default', ['concat']);

};
